### PR TITLE
Update sharp dependency

### PR DESCRIPTION
**Pull request by xemle**
Update sharp dependency to fix issues

Upgrading sharp solves my issues while calculating lots of phashes.

### CODE REVIEW

**Comment by btd** [comment]
Change itself is ok' could you just elaborate on issues you have?

**Comment by xemle** [comment]
Thanks for the reply (and this awesome lib).

My setup is a image stream pipe with image processing steps including calculation of phashes. After few phash calculations the pipe stucks with your older provided sharp dependencies.

This issue is solved due a newer sharp version and the pipe can complete.Since this issue occurs in a stream pipe with lots of image and its operations, I was not able to isolate this issue so far. Due lack of time for this spare time project I will also skip further investigation for now.

I am fine if you reject this PR due a missing reproducible proof. I would reopen this issue, if I can proof this issue ;-)

**Comment by xemle** [comment]
I close this issue, since I discovered other problems with sharp and the error message

```
sharp.node: undefined symbol: vips_foreign_heif_compression_get_type
```

I will reopen this issue on updates

**Comment by btd** [comment]
Hmm, ok. Feel free to bring issue.
For my usecase if used this lib to process social images from diffferent users, sometimes up to 100k per day. Not sure why you had this issue. It could be something with image format or image specifically.

**Comment by xemle** [comment]
OK. I found the problem causing this issue. It was the different minor version of sharp. My project was using a sharp version 0.23.x while sharp-phash uses sharp version 0.22.0. As noted in the sharp issue [Multiple versions of sharp in node_modules cause "Incompatible library version" error #1680](https://github.com/lovell/sharp/issues/1680#issuecomment-487701749) this is problematic:

> Two different versions of sharp using different prebuilt versions of libvips and its dependencies, e.g. v0.21.x and v0.22.x, will not be able to co-exist in the same Node process (although they could live alongside each other in node_modules filesystem).

I was able to fix the problem by using [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions). Do you any other idea how to solve it?

**Comment by btd** [comment]
Well, i think it is quite easy. We just need a way to allow to provide sharp to user.

**Comment by btd** [comment]
I just published 1.1.0

**Comment by xemle** [comment]
That are awesome news! Thank you very much for 1.1.0 and the ability to inject a sharp version. You saved my day :-)

**Pull request closed without merging**
